# GCRG Open Science Plan

The Global Change Research Group strives for an open science policy that makes our science accessible and reproducible and that allows us to collaborate with our future selves and with our colleagues. To assist in achieving that aim, we use the following practices.


## Key resources
1. Lab notebook
1. Shared Google Drive (Global Change Research Group)
1. GitHub repository
1. Working location (laptop, scientific workstation, cluster, etc.)
1. Backup location (Bishop, a PbSci storage server that is backed up offsite. This may change to Rufus, a different storage server, in the future.)

## Project organization

1. Lab notebooks are maintained each day; tracking progress, daily learnings, what was accomplished, and/or what goal was worked towards. These can be Google Docs, physical notebooks, text files, Evernote, Jupyter notebooks, etc.
   1. Lab notebooks are digitally backed up, regardless of initial format

1. Each new project gets a GitHub repository in the [pinskylab organization](https://github.com/pinskylab)
   1. This practice facilitates collaboration, sharing, data traceability, and maintenance of institutional knowledge.
   1. Repos can be public or private
   2. A [CITATION.cff](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) clarifies how to cite the repo. We apply authorship criteria similarly as for papers (e.g., first author is the lead).
   1. Data processing is accomplished through the use of scripts, not manual manipulation
      1. This helps to ensure the reproducibility of our methods
   1. Repos have a logical directory format, e.g., scripts, data, data_dl (for data to download from other sources), output, and figures.
   1. Figures, tables, and key output files (e.g., genotypes, statistical tables, etc.) are included in the repo.
   1. A README.md in each directory (including the top directory) 
      1. explains the purpose of each file and sub-directory
      1. describes how to run the scripts, which input files they depend on, and which output files they produce (i.e., a list of step-by-step instructions)
      1. describes all data files in the directory and includes links to any data files not in the repo along with instructions for how to download and set them up in the repo so that scripts can run
      1. includes links to relevant papers and preprints (most relevant for top level)
      1. has contact information for authors and data creators, as necessary (most relevant for top level)
      1. defines data columns, including units, of all data files and basic methods used for data collection
      1. has link for and version numbers of any software or packages needed for running codes or scripts
      1. describes the compute environment in which the scripts and software were run
   1. If the repo is included in a publication, we also archive it with a DOI on, for example, [Zenodo](https://www.zenodo.org) (see [here](https://github.com/pinskylab/pinskylab_methods/blob/master/cookbook.md#archiving-a-git-repo-with-zenodo-for-a-publication) for instructions).
   2. We add a license to each git repo, e.g., MIT or CC BY-NC 4.0, to clarify how the material can be reused. See guidance from [Creative Commons](https://creativecommons.org/share-your-work/cclicenses/), [Github](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository), and [R Packages book](https://r-pkgs.org/license.html#code-you-write).
3. We write collaborative manuscripts in the GCRG Shared Google Drive
4. Presentations are typically made in Google Slides in the GCRG Google Drive (Presentations/) allowing lab members easy access to useful graphics
   1. Name the file in the format YYYY-MM-DD_presentername_occasion, eg, 2023-01-07_Pinsky_AmNat
5. Before matriculation, we ensure all projects, code, data, papers, etc. are available and fully documented

## Data
Data used in support of a project is:

1. Saved in an appropriate, non-proprietary format with accompanying metadata (e.g., csv rather than Excel)
1. Raw data is stored in or linked from the GitHub repository associated with the project
   1. Raw data files under the Github file size limit (<100MB) are stored in a data/ directory
   1. Larger files are stored in a data_largefiles/ directory (not tracked by Git by using the .gitignore file) in at least two places 
         - where the analysis is occurring (e.g., laptop or scientific workstation), and
         - either one of (we document this arrangement clearly in the relevant data_largefiles/README.md file of the git repo):
            - on [FigShare](https://figshare.com/), linked from the relevant GitHub readme.
            - on NCBI for raw sequencing reads. Upload them soon after receiving, possibly with an embargo, with the accession numbers documented in the relevant README.md. Metadata for the samples goes on [GEOME](https://geome-db.org).
            - another public data repository, with a link pointing to the data from the git readme.
        - if FigShare, NCBI, or other public data repositories are not appropriate, we can use the UCSC PbSci Bishop data server. Data is stored in bio-globalchange/data_largefiles/ in a subdirectory whose name matches the Git repo name.
   1. If data from an external or public source is being used, it is stored in a data_dl/ directory (not tracked by Git). We clearly and unambiguously describe the data source in the data_dl/README.md file by providing links, version numbers, descriptions for access/download, or other details to ensure reproducibility. If you're worried the data won't be available in the future, follow one of the two previous bullet point approaches.
   3. Metadata is stored in the same directory as the raw data, typically in a README.md file that describes the data in each column, units, coordinate reference system (CRS, for GIS data), and other details needed to understand the file
   4. Processed or cleaned data is stored in a separate directory, e.g., output/ or similar, to differentiate from raw data


## Code
All code used or developed in support of the project is:

1. Well commented and complete
1. Versioned in the project's git repository
1. Described in the README.md file to explain what each script does, what language was used, what software and package versions were used, etc.
1. Tested! Can at least one other person (more is better) complete your analysis on a different computer?

## Backups
We store our raw data and scripts in at least two locations.

1. Most of our work is on Github or Google Drive. Both are backed up monthly to the UCSC PbSci Bishop file server.
1. Raw data files too large for Github and Drive are stored in two locations (see Data section above)
