# Some notes for a Ph.D.
Notes written by Malin Pinsky, 2013-2024

## Skills to develop
My goal is to help you understand and succeed in our discipline as it is now, while also empowering you with the agency to reshape it in the image of all of us.

- project design
- data analysis and interpretation
- oral presentation: see Scientific presentation tips (to add)
- grant-writing
- manuscript writing
- collaborating and networking in academia
- teaching
- peer reviewing

*(see our onboarding guide for resources)*

## Expectations/Milestones
- Throughout
  - Participate in the community and build your professional network
    - attend all seminars, meet most or all speakers, come to lab meetings, work from CBB
		- Contribute to the community: clean up after yourself, do maintenance, do chores, etc.
	- Reproducibility for collaboration with future self, with others in lab, with others outside lab (see the [Data Management Guide](https://github.com/pinskylab/how_we_work/blob/master/data-management.md))
	- Practice any talks and present any posters to the lab, before you take them to a conference
  - This is will be substantially more work than a 9-5 job or taking classes as an undergraduate or MS student
- First year
  - First meeting topics
    - Expectations for me from you
    - Expectations for you from me
    - Your expectations for the PhD experience
	  - What you want to learn from the PhD
    - Where your are tentatively heading
    - First year project?
    - If you have fears, concerns, questions, or just want to talk, please come find me. If you’re upset, please tell me.
  - Apply to fellowships (fall)
  - First year talk (lab meeting or other venue)
  - Start and perhaps finish a first year project that is publishable
  - Comprehensive exam on the first-year courses
  - Read widely across the literature
- Second year
    - Finish courses
    - First year project written up and potentially submitted
    - Read widely and design a dissertation proposal
    - Attend a conference, present a talk or poster
- Third year
    - Write dissertation proposal and defend it, “Qualifying exam"
    - Continue research
    - Attend a conference and present 
- Fourth year
    - Continue research
    - Submit papers
    - Attend a conference and present 
- Fifth year
    - Finish research
    - Submit remaining papers
    - Attend a conference and present 
    - Apply for postdoc fellowships (fall) and contact potential mentors, or network and do informational interviews for non-academic opportunities 
    - Defend dissertation!
        - At least 6 weeks in advance of defense: last draft of dissertation chapter to Malin. Others already done.
        - Defense date is tentative until
        	- Full dissertation written
         	- At least 2 chapters submitted for publication
          	- All chapters comply with our [Data Management Plan](https://github.com/pinskylab/how_we_work/blob/master/data-management.md)

## 6-Month Check-ins
At the end of the fall and spring, we take a meeting to step back from the details and think about big picture career trajectories. It’s a good chance to go back the goals you wrote for yourself, think about your progress, and think about whether they’re still the right goals for you. Please start a running document of your goals in our Google Drive (how_we_work/Group_member_goals/, make a copy of the template and add your name to the title) and share it with Malin.

This is your meeting to use as you want, but I often find it useful to loosely structure the meeting like this: 

- First 1/3: Highlights from the semester/last six months:
  - What have you done?
  - What have you learned?
  - What connections have you made?
- Last 2/3: Plans for the next six months:
  - What do you want to do?
  - What do you want to learn?
  - What connections do you want to make?
  - How can I support you in that?
- Also let me know if you want me to think about answers to any questions.
- Funding plan during each end-of-year checkin

## Training resources
-  Academic career development resources through the NCFDD. Activate your account through UCSC [here](https://senate.ucsc.edu/committees/cca-committee-on-career-advising/faculty-career-resources/facultydevelopmentdiversity.html), including resources for graduate students like (https://www.ncfdd.org/dissertation-success-members).
- Leadership
	- USFWS National Conservation Training Center
	- Heemstra, J. 2025. Labwork to Leadership. Harvard University Press.
	- [Making the Right Moves: A Practical Guide to Scientific Management for Postdocs and New Faculty, Second Edition](https://capd.mit.edu/resources/making-the-right-moves-a-practical-guide-to-scientific-management-for-postdocs-and-new-faculty-second-edition/)
	- Buckingham and Coffman. 1999. First, Break All the Rules: What the World's Greatest Managers Do Differently. Simon & Schuster.

- Communication
	- [COMPASS](https://www.compassscicomm.org/)
- [TULIP](https://www.labex-tulip.fr/internet6_national_labex_tulip-eng/the-labex/training-and-higher-education) summer school on interdisciplinary ecology
- [SIIECS](https://www.ices.dk/community/groups/Pages/SIIECS.aspx): early career society of ICES
- Michigan State University Kellogg Biological Station
		- Jennifer Hoey enjoyed them. Not offered every year?
		- Part of CIC (Committee on Institutional Cooperation), so Rutgers students get an "in"
- [Santa Fe Institute's Complex Systems Summer School](https://www.santafe.edu/engage/learn/programs/sfi-complex-systems-summer-school)

## Course ideas
- At UCSC
	- Stats and applied math 
		- STATS 206 Applied Bayesian Stats (with David Draper) (can get permission to skip prereqs)
 		- STATS 203 Introduction to Probability Theory
   		- STATS 204 Introduction to Statistical Data Analysis (includes some R)
   		- STATS 206B Intermediate Bayesian Stats
    		- EART125 - Statistics and Data Analysis in the Geosciences (Matthew Clapham)
      		- OCEA 267 Applied Environmental Time Series Analysis (Claudie Beaulieu)
- Off campus
	- Stats
   		- https://www.statstree.org/
		- Tyre, ecological statistics in R, online, University Nebraska Lincoln
  		- [Biostats suggestions from Ecology](https://dynamicecology.wordpress.com/2021/07/28/stage-setting-readings-and-videos-to-kick-off-an-intro-biostats-course-here-are-mine-please-share-your-suggestions/)
		- Two recommended stats books from economics
  			- Pindyck, R.S., Rubinfeld, D.L., 1998. Econometric Models and Economic Forecasts, 4th ed. McGraw-Hill New York, NY
     		- Cameron, A.C., Trivedi, P.K., 2005. Microeconometrics methods and applications. Cambridge University Press, NY
		- Coursera
			- Brian Caffo, Mathematical biostatistics boot camp 1 and 2
				- 7 weeks, taught several times per year
				- Recommended by: Columbia Univ PhD student: The teacher and format are very good. But it is pretty elementary; covers what you would learn in a rigorous basic stats course (comment on boot camp 1)
			- Roger Peng, Computing for data analysis
				- in R, generally taught Sept, 4 weeks
				- Recommended by: Tia-Lynn Ashman lab member says excellent, pretty hard, 10-15 hrs per week, covers both data management and stats
			- Jeff Leek, Data analysis
				- in R, generally taught Oct, 8 weeks
				- Recommended by: Brian Caffo read his statistics blog http://simplystatistics.org
			- John McGready, Statistical Reasoning
				- seems to be not available every time I check. aimed at public health
				- Recommended by: Brian Caffo, fantastic course
			- Note: Peng and Leek are collaborators, both at Johns Hopkins. They additionally teach the below but Rae Winfree has not found out more on these courses:
				- R programming
				- Getting and cleaning data

## Funding ideas
- Travel funding
	- American Society of Naturalists: regional conference funding; workshop funding
	- UCSC EEB
	- ICRS travel funding
	- [Travel funding for ECRs](https://docs.google.com/spreadsheets/d/19ye-FrPi0WDrjSV8V3xi3HDMcw0i1y-QkAVZOyPRR20/edit#gid=0)
	- Journal of Marine Science and Engineering: http://www.mdpi.com/journal/jmse/awards
 	- [Western Association of Marine Labs (WAML)](http://waml.naml.org/members/studentsupport.php), due Oct. 31

- Research funding
	- Internal
		- UCSC Committee On Research $2000/year (Malin can apply in ~May). No proposal needed.
  		- UCSC Committee on Research Large Grants Program: $12000 for two years. Malin can apply. 2 pp application.
    		- Inst. of Marine Science Student Research & Education Award
		- UCSC EEB summer funding
  		- UCSC Activating Innovative Graduate Research Award (AIGRA)
  		- [Keeley Coastal Scholars](https://socialsciences.ucsc.edu/support-us/awards/student-awards/keeley-coastal-scholars/index.html): $1000-$4000 for underrepresented undergraduates or grad student
    		- [Hammett Awards through ENVS](https://envs.ucsc.edu/about/awards/index.html)
  		- UC Alianza MX Short-Term Research in Mexico: covers living expenses, travel, and other related expenses for up to three months to accomplish specific laboratory, library, or field research at partner institutions in Mexico. Calls often go out in February, due in March.
    	- Daniel Briggs Memorial Award for summer research or policy work related to coastal sustainability. Due ~ March. $500-$1000.
    	- [Sooy Fellowship](https://science.ucsc.edu/research-opportunities/rebecca-and-steve-sooy-graduate-fellowship-in-marine-mammals/) for marine mammals
	- [Women Divers Hall of Fame Scholarships and Training Grants](http://www.wdhof.org/wdhof-scholarshipDesc.aspx)
	- AMNH Lerner Grey
	- [Sigma Xi Grants in Aid of Research](https://www.sigmaxi.org/programs/grants-in-aid-of-research/apply)
	- [Western Association of Marine Labs (WAML)](http://waml.naml.org/members/studentsupport.php), due Oct. 31
 	- Explorers Club [Stephenson Explorers Advancement Program](https://www.explorers.org/grants/the-stephenson-explorers-advancement-program/) and [Kensington Conservation Grant](https://www.explorers.org/grants/kensington-explorers-club-grant/)
  	- American Philosophical Society’s Lewis and Clark Fund for Exploration and Field Research
	- Dr. Earl H. Myers and Ethel M. Myers Oceanographic & Marine Biology Trust ($2600 in 2024)
	- Washington Biologists Field Club: Mid-Atlantic. https://www.pwrc.usgs.gov/resshow/perry/bios/WBFCHome.htm
	- P.E.O. Scholar Award: women w/in 2 years of finishing a PhD
 	- [Graduate Women in Science National Fellowship Program](https://www.gwis.org/page/fellowship_program)
 	- Gloria Barron Wilderness Society Scholarship (Wilderness Society), $25000 scholarship for research supporting wilderness conservation.
	- Rafe Sagarin Fund: http://www.rafeinnovativeecologyfund.org/
	- Society for Study of Evolution: http://www.evolutionsociety.org/content/society-awards-and-prizes/graduate-research-excellence-grants.html
		- Rosemary Grant awards, year 3+, up to $3500
	- American Genetic Association EECG award (due Dec 15)
	- [AFS Steven Berkeley Marine Conservation Fellowship](https://mfs.fisheries.org/?page_id=155): also open to international students
	- International Coral Reef Society student fellowship
 	- [Beneath the Sea Scholarship](https://beneaththesea.us/scholarships/)
- Fellowships (stipend)
	- Internal
 		- Dissertation Year Fellowship
   		- Pedagogy fellowships through The Learning Center
     	- [Sooy Fellowship](https://science.ucsc.edu/research-opportunities/rebecca-and-steve-sooy-graduate-fellowship-in-marine-mammals/) for marine mammals
	- NSF GRFP
		- advice: https://ojs.library.queensu.ca/index.php/IEE/article/view/6349#.WG57HQnKFbg
	- NDSEG: read carefully to find the best match BAA category. We have been quite successful with this one.
 	- DOE Computational Science Graduate Fellowship (4 years)
	- HHMI Gilliam Fellowships (apply in 2nd or 3rd year as a advisor-mentee pair, due in early December)
	- CA Sea Grant Graduate Fellowships: has a focus on CA
	- Smithsonian (post-qualifying): https://fellowships.si.edu/opportunity/big-ten-academic-alliance-smithsonian-fellowship
 	- [ACM SIGHPC Computational & Data Science Fellowships](https://www.sighpc.org/for-your-career/fellowships) 	
	- EPA STAR
	- NOAA Nancy Foster: with a National Marine Sanctuary
	- NOAA Margaret Davidson: with a National Estuarine Research Reserve
 	- NMFS-Sea Grant Fellowship in Population and Ecosystem Dynamics: for more quantitative projects and students
   - DOE computational science (includes biomathematics)
   - [The Hertz Foundation Graduate Fellowships](https://www.hertzfoundation.org/the-fellowship/)
   - [Quad Fellowship](https://www.quadfellowship.org/)
   - Paul & Daisy Soros Fellowship for New Americans
	
## Conference ideas
- American Society of Naturalists (January)
- Ecological Society of America (August)
- Evolution (June)
- Species on the Move (every three years or so)
- International Biogeography Society Meeting
- Gordon Conference in Marine Global Change (July)
- Effects of Climate Change on the World's Oceans (ECCWO) (ICES/PICES): next to be in 2027 or 2028
- American Genetics Association
- American Fisheries Society
- Western Society of Naturalists (marine biology, mostly west coast)
- Benthics (marine biology, mostly east coast)
- specialized
	- Western Indian Ocean Marine Science Assoc (WIOMSA)
	- Asian Pacific Coral Reef Society (APCRS)

## Awards
- ASN Jasper Loftus-Hills, <3yrs from PhD, Jan 31
- ESA Early Career Fellow
- ICRS Awards (Feb. 15)

## Postdoc funding
- Life Sciences Research Foundation: open to non-US citizens, 3 years, network-building
- NSF
- David H. Smith
- Liber Ero
- Fulbright
- iDiv fellowships
- HIFMB (Helmut Hillebrand center in Germany)
- SESYNC postdocs
- Institutional fellowships
	- UT Austin integration biology
	- U Michigan
	- UC Berkeley
	- Harvard sustainability
  - UVM Voss Postdoctoral Fellows
	- others...
- Policy
	- AAAS Science-Policy Fellowship
	- Knauss Marine Policy Fellowship
- https://asntech.github.io/postdoc-funding-schemes/

## Jobs
- [ecoevojobs.net](ecoevojobs.net) for academic jobs
- https://sevenseasmedia.org/ocean-jobs/#s=1 
- data science
	- Insight Data Science Fellowship
- [ECOLOG-L](https://www.esa.org/membership/ecolog/) for ecology
- [evoldir](https://evol.mcmaster.ca/evoldir.html) for evolution
- [ICRS SECC job board](coralreefsecc.org/jobboard,) for coral reef jobs
- Oceanography jobs lists from Dalhousie: https://www.phys.ocean.dal.ca/hotlists/jobs.html
- NOAA
  - At least some of the NOAA contract jobs are posted at http://www.oceanassoc.com/Jobs/jobslist.html
  - Recently filled jobs are listed here: http://www.oceanassoc.com/Jobs/jobslistrecentlyfilled.html
  - get to know NOAA colleagues through the Fisheries Cooperative Program at UCSC (FCP)
